# -*- coding: utf-8 -*-
"""LegalBERT SNLI fine-tuning

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1bkrvzP8ehTF39NmjYVRJQUp9ERP9fT2G
"""

import os
print(os.getcwd())

from google.colab import drive
drive.mount('/content/drive')

! huggingface-cli login

!pip uninstall -y datasets fsspec
!pip install --no-cache-dir git+https://github.com/huggingface/datasets.git
!pip install -q transformers evaluate

!pip install transformers

import transformers
print(transformers.__version__)

from datasets import load_dataset
from transformers import AutoTokenizer, AutoModelForSequenceClassification, TrainingArguments, Trainer
import numpy as np
import evaluate
from sklearn.metrics import accuracy_score

from transformers import AutoTokenizer, AutoModelForSequenceClassification, Trainer, TrainingArguments

from datasets import load_dataset
dataset = load_dataset("snli")
dataset = {split: ds.filter(lambda x: x["label"] != -1) for split, ds in dataset.items()}

tokenizer = AutoTokenizer.from_pretrained("nlpaueb/legal-bert-base-uncased")

def tokenize_fn(example):
    return tokenizer(
        example["premise"],
        example["hypothesis"],
        truncation=True,
        padding="max_length"
    )

tokenized_dataset = {
    split: ds.map(tokenize_fn, batched=True)
    for split, ds in dataset.items()
}

model = AutoModelForSequenceClassification.from_pretrained(
    "nlpaueb/legal-bert-base-uncased",
    num_labels=3
)

metric = evaluate.load("accuracy")
def compute_metrics(eval_pred):
    logits, labels = eval_pred
    predictions = np.argmax(logits, axis=1)
    return metric.compute(predictions=predictions, references=labels)

from transformers import TrainingArguments

training_args = TrainingArguments(
    eval_strategy="epoch",
    save_strategy="epoch",
    per_device_train_batch_size=32,
    per_device_eval_batch_size=64,
    num_train_epochs=10,
    weight_decay=0.01,
    logging_dir="./logs",
    logging_strategy="epoch",
    load_best_model_at_end=True,
    metric_for_best_model="accuracy",
    report_to="none",
    fp16=True,
    dataloader_num_workers=4,
)

from transformers import Trainer

trainer = Trainer(
    model=model,
    args=training_args,
    train_dataset=tokenized_dataset["train"],
    eval_dataset=tokenized_dataset["validation"],
    tokenizer=tokenizer,
    compute_metrics=compute_metrics
)

import os
os.environ["WANDB_DISABLED"] = "true"
trainer.train()
trainer.save_model("/content/drive/MyDrive/legalbert-snli-finetuned")
tokenizer.save_pretrained("/content/drive/MyDrive/legalbert-snli-finetuned")

model_path = "/content/drive/MyDrive/legalbert-snli-finetuned"
tokenizer = AutoTokenizer.from_pretrained(model_path)
model = AutoModelForSequenceClassification.from_pretrained(model_path)

def compute_metrics(pred):
    preds = np.argmax(pred.predictions, axis=1)
    return {"accuracy": accuracy_score(pred.label_ids, preds)}

test_dataset = tokenized_dataset["test"].remove_columns(["premise", "hypothesis", "label"])
test_dataset = test_dataset.add_column("labels", dataset["test"]["label"])
test_dataset = test_dataset.with_format("torch")

trainer = Trainer(
    model=model,
    tokenizer=tokenizer,
    compute_metrics=compute_metrics
)

metrics = trainer.evaluate(eval_dataset=test_dataset)
print(f" Test Accuracy: {metrics['eval_accuracy']:.4f}")